*&---------------------------------------------------------------------*
*& Include          MZ12AL10_CCOMEX_TOP
*&---------------------------------------------------------------------*
TABLES: ZTBCOMEX_10, ZTBCOMEX_10_LOG,
        VBAK, VBKD, KUAGV,
        VBAP, RV45A, MARA.

DATA: V_VBELN LIKE VBAK-VBELN.

DATA: P_AUART     TYPE VBAK-AUART, " TIPO DOCUMENTO
      P_VKORG     TYPE VBAK-VKORG, " ORGANIZAÇÃO DE VENDAS
      P_VTWEG     TYPE VBAK-VTWEG, " CANAL DISTRIBUIÇÃO
      P_SPART     TYPE VBAK-SPART, " DIVISÃO
      P_EMI_KUNNR TYPE KUAGV-KUNNR," EMISSOR DA ORDEM
      P_REC_KUNNR TYPE KUWEV-KUNNR." RECEBEDOR DA ORDEM

DATA: P_NSOL TYPE ZTBCOMEX_10-NSOL.

* ESTRUTURA TABLE CONTROL MATERIAL TELA 9100
TYPES: BEGIN OF TY_MATE_TC,
  MARK TYPE FLAG,
  MATNR LIKE VBAP-MATNR,    " NUMERO DO MATERIAL
  KWMENG LIKE RV45A-KWMENG, " QUANTIDADE
  PRCTR LIKE VBAP-PRCTR,    " CENTRO
  PSTYV LIKE VBAP-PSTYV,    " CATEGORIA
  "--- AUTO ----"
  ARKTX LIKE VBAP-ARKTX," DESCRIÇÃO ( AUTO )
  END OF TY_MATE_TC.

DATA: MATE_TC_ITAB TYPE STANDARD TABLE OF TY_MATE_TC,
      MATE_TC_WA TYPE TY_MATE_TC.
DATA: MATE_TC_COPIED.

DATA:     MATE_TC_INT_LINES  LIKE SY-LOOPC.
DATA:     OK_CODE LIKE SY-UCOMM.

*&SPWIZARD: DECLARATION OF TABLECONTROL 'MATE_TC_INT' ITSELF
CONTROLS: MATE_TC_INT TYPE TABLEVIEW USING SCREEN 9100.


* ESTRUTURA TABELA INTERNA DE LOG
*TYPES: BEGIN OF TY_LOG,
*  NSOL TYPE ZTBCOMEX_10_LOG-NSOL,
*  USUARIO TYPE ZTBCOMEX_10_LOG-USUARIO,
*  STATUS TYPE ZTBCOMEX_10_LOG-STATUS,
*  MESSAGE TYPE ZTBCOMEX_10_LOG-MESSAGE,
*  DATA TYPE ZTBCOMEX_10_LOG-DATA,
*  HORA TYPE ZTBCOMEX_10_LOG-HORA,
*  END OF TY_LOG.

DATA: T_LOG TYPE TABLE OF ZTBCOMEX_10_LOG,
      WA_LOG TYPE ZTBCOMEX_10_LOG.
DATA: T_COMEX TYPE TABLE OF ZTBCOMEX_10,
      WA_COMEX TYPE ZTBCOMEX_10.


data: V_PBO_EXECUTED TYPE ABAP_BOOL. " Identifica se o PBO ja foi executado.